name: twoq_tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
   runs-on: ubuntu-latest

   container:
     image: ubuntu:22.04

   steps:
   - name: Checkout sources
     uses: actions/checkout@v4

   - name: Install dependencies
         run: |
           apt-get update
           apt-get install -y \
             build-essential \
             cmake \
             valgrind \
             git

   - name: Configure
     run: |
      cmake -DCMAKE_BUILD_TYPE=Release -S . -B build

   - name: Build
     run: |
      cmake --build build --target 2q

   - name: Run tests under Valgrind
     run: |
      cd build
      valgrind --leak-check=full ./2q
